name: GitHub Actions Demo
on: [push]
jobs:
  Build-DSC:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt install gnupg dput dh-make devscripts lintian
      - run: sudo apt install dpkg-dev
      - run: mkdir ${{ github.home }}/workspace
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: cp ${{ github.workspace }}/* ${{ github.home }}/workspace
      - run: rm -rf ${{ github.home }}/workspace/repository-setup
      - run: cd ${{ github.home }}/workspace
      - run: debuild -S
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."