name: GitHub Actions Demo
on: [push]
jobs:
  Build-DSC:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt install gnupg dput dh-make devscripts lintian
      - run: sudo apt install dpkg-dev
      - run: mkdir workspace
      - run: cd workspace
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: rm -rf ${{ github.workspace }}/workspace/repository-setup
      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v4
        with:
          gpg_private_key: ${{ secrets.DRIVER_GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.DRIVER_GPG_PASSPHRASE }}
      - run: debuild -S
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: List result files
        run: |
          ls ${{ github.home }}
      - name: List result files 2
        run: |
          ls ${{ github.workspace }}/workspace
      - run: echo "🍏 This job's status is ${{ job.status }}."