name: Debian Source Package and Repo build
on: [push]
jobs:
  Build-DSC-Repo:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt install gnupg dput dh-make devscripts lintian
      - run: sudo apt install dpkg-dev
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          path: workspace
      - run: mv ${{ github.workspace }}/workspace/repository-setup ${{ github.workspace }}/repository
      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v4
        with:
          gpg_private_key: ${{ secrets.DRIVER_GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.DRIVER_GPG_PASSPHRASE }}
      - run: debuild -S
        working-directory: ${{ github.workspace }}/workspace
      - run: echo "DSC package built!"
      - name: List files in the repository
        run: ls ${{ github.workspace }}
      - name: List result files
        run: ls ${{ github.home }}
      - name: List result files 2
        run: ls ${{ github.workspace }}/workspace
      - run: sudo apt install reprepro
      - run: reprepro --basedir ${{ github.workspace }}/repository includedsc ORCA ${{ github.workspace }}/orca-driver_0.0.0.1.dsc
        working-directory: ${{ github.workspace }}/repository
      - name: List result files 3
        run: ls ${{ github.workspace }}/repository