name: Debian Source Package and Repository build
on: [push]
jobs:
  Build-DSC-Repo:
    runs-on: ubuntu-latest
    steps:
      - name: Install prerequisites
        run: |
          sudo apt update
          sudo apt install gnupg dput dh-make devscripts lintian dpkg-dev reprepro dkms
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          path: workspace
      - name: Relocate repository building configuration
        run: mv ${{ github.workspace }}/workspace/repository-setup ${{ github.workspace }}/repository
      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.DRIVER_GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.DRIVER_GPG_PASSPHRASE }}
      - name: Build package
        run: debuild -S
        working-directory: ${{ github.workspace }}/workspace
      - name: Retrieve package version
        run: |
          echo "VERSION=$(cat debian/files | sed 's/orca-driver_\(.*\)*_.*/\1/')" >> $GITHUB_OUTPUT
        id: version
        working-directory: ${{ github.workspace }}/workspace
      - name: Check out target repository code
        uses: actions/checkout@v2
        with:
          path: target
          repository: DeGirum/DeGirum.github.io
          token: ${{ secrets.PRIVATE_TOKEN }}
      - name: Prepare repository build
        run: |
          rm -rf ${{ github.workspace }}/target/docs/apt-repo
          mv ${{ github.workspace }}/repository ${{ github.workspace }}/target/docs/apt-repo
      - name: Build repository
        run: reprepro -V --basedir ${{ github.workspace }}/target/docs/apt-repo includedsc ORCA ${{ github.workspace }}/orca-driver_${{ steps.version.outputs.VERSION }}.dsc
        working-directory: ${{ github.workspace }}/target/docs/apt-repo
      - name: Clean up repository build files
        run: |
          rm -rf ${{ github.workspace }}/target/docs/apt-repo/db
          rm -rf ${{ github.workspace }}/target/docs/apt-repo/conf
      - name: Commit results
        run: |
          git config --global user.name 'Alexander Bolotov'
          git config --global user.email 'bolotov@degirum.com'
          git switch -c apt-staging-branch
          git commit -am "Automated diver source package commit"
          git push --set-upstream origin apt-staging-branch
        working-directory: ${{ github.workspace }}/target
      - run: echo "Upload completed!"
